title: smogsuper
email: 1938508721@qq.com
baseurl: /  # the subpath of your site, e.g. /blog/
github_username:  smogsuper
markdown: kramdown
paginate: 13
paginate_path: "/page:num" 
highlighter: pygments
